### ISSUE TITLE
What are the meaning of the fields in default_config.yml?

### ISSUE THREAD

**Issue by kkew3** [ucbdrive/scalabel#48]
Here is the content of `app/config/default_config.yml`. Could anyone explain what are `data`, `src`, and `database`? (what is the base directory these fields are relative to? what are the meaning of these fields?) I didn't find how to set them in documentation. Thanks in advance!

```yaml
---
port: 8686
data: "../../.scalabel.data"
src: "."
database: "local"
...
```
